version: '3'

services:
  nodejs:
    image: petrkalinin/algoprog-test
    container_name: nodejs
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://db/algoprog_archive
      - MONGODB_USERS_URL=mongodb://db/algoprog
    ports:
      - "3000:3000"
    networks:
      - app-network
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: always
    volumes:
      - data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
