apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algoprog-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - test.algoprog.ru
    - www.algoprog.ru
    - adina.algoprog.ru
    - algoprog.ru
    - online.mathncode.kz
    secretName: test-tls
  rules:
  - host: algoprog.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs
            port:
              number: 3000
  - host: adina.algoprog.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-adina
            port:
              number: 3000
  - host: online.mathncode.kz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-adina
            port:
              number: 3000
  - host: www.algoprog.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs
            port:
              number: 3000
