apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-adina
  name: nodejs-adina
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-adina
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: nodejs-adina
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: db
            - name: MONGO_USERS_HOST
              value: db
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER_ADINA
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD_ADINA
            - name: NODE_ENV
              value: production
            - name: ACCUMULATE_REQUESTS
              value: "1"
            - name: ADMIN_TELEGRAM_ID
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: ADMIN_TELEGRAM_ID
            - name: FORCE_HTTPS
              value: "1"
            - name: GRAPHITE_PREFIX
              value: algoprog_adina
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: TELEGRAM_TOKEN_ADINA
            - name: USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: USER_AGENT_ADINA
          image: petrkalinin/algoprog-adina
            - name: INVOICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: INVOICE_PASSWORD
            - name: INVOICE_IP_DATA
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: INVOICE_IP_DATA
            - name: INVOICE_IP_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: INVOICE_IP_SIGNATURE
          imagePullPolicy: "Always"
          name: nodejs-adina
          ports:
            - containerPort: 3000
          resources: {}
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2
      initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'until nc -z db:27017; do echo waiting for db; sleep 2; done;']          
      restartPolicy: Always
status: {}
