name: "Build docked image from adina branch"

on:
  push:
    branches:
      - 'adina'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: petrkalinin/algoprog-adina:latest,petrkalinin/algoprog-adina:${{ github.sha }}
          cache-from: type=registry,ref=petrkalinin/algoprog-adina:latest
          cache-to: type=inline

      - 
        name: Set kubectl context
        uses: azure/k8s-set-context@v3
        id: setcontext
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}
          
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Deploy to k8s
        uses: Azure/k8s-deploy@v4.3
        with:
          manifests: |
            k8s/nodejs-deployment.yaml
            k8s/nodejs-service.yaml
          images: 'petrkalinin/algoprog-adina:${{ github.sha }}'
          action: deploy
