name: "Build docked image from k8s branch"

on:
  push:
    branches:
      - 'k8s'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: petrkalinin/algoprog-test:latest,petrkalinin/algoprog-test:${{ github.sha }}
          cache-from: type=registry,ref=petrkalinin/algoprog-test:latest
          cache-to: type=inline

      - 
        name: Set kubectl context
        uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - 
        name: Deploy to k8s
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            k8s/nodejs-deployment.yaml
            k8s/nodejs-service.yaml
          images: 'petrkalinin/algoprog-test:${{ github.sha }}'
          kubectl-version: 'latest'
